version: '3'
services:
  storage:
    image: postgres:16.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env.db
    ports:
      - "5432:5432"

volumes:
  postgres_data: